[package]
name = "rusty-c-macro"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
peg = "0.7"
bit-vec = "0.6"
check_keyword = "0.1"
bitflags = "1.3"
rt-format = "0.1"

[features]
debug = []
